Adding ignore flag for CI to be able to mark build stable afterwards
r0bb3n/sonar-quality-gate-maven-plugin pull request #114
Opened 2021-07-08 18:14 UTC by markri

This adds the possibility to ignore the outcome of a failing quality gate (so it won't result in a build failure). As I'd like to mark my build "unstable" in Jenkins based on the console output alone. (Jenkins doesn't allow to override the build status FAILURE to UNSTABLE)

@r0bb3n Hope this can be merged

2021-07-14 20:18 UTC, r0bb3n requested changes
@markri 

First of all thank you for using my plugin and taking the effort to contribute here.

There are a couple of things to cover, before I can accept the PR (and create a new release):

1. rename the property
    * please see my inline comment at the declaration
2. add a test, that covers this new behavior
    * extend the class `SonarQualityGateMojoExecuteTest` ([link](https://github.com/r0bb3n/sonar-quality-gate-maven-plugin/blob/master/src/test/java/org/r0bb3n/maven/SonarQualityGateMojoExecuteTest.java)) with a new test method and use the method `mojoExecuteWithProjectKeyAndPullRequestWarn` ([link](https://github.com/r0bb3n/sonar-quality-gate-maven-plugin/blob/b90c7f7ef38a7d66038d110eccd720e7403264cc/src/test/java/org/r0bb3n/maven/SonarQualityGateMojoExecuteTest.java#L134)) as template
3. update the `README.md` by adding the new parameter in the section [Plugin parameters](https://github.com/r0bb3n/sonar-quality-gate-maven-plugin/blob/master/README.md#plugin-parameters)
4. update the `CHANGELOG.md` section "Unpublished" with a new section "Added", where your feature is listed
    * for more details about the format, just check https://keepachangelog.com/en/1.0.0/

2021-07-15 10:51 UTC, r0bb3n commented on src/main/java/org/r0bb3n/maven/SonarQualityGateMojo.java
> +        getLog().info(message);
Please change to `warn`, since this is more than `info`
```suggestion
        getLog().warn(message);
```

2021-07-15 11:51 UTC, r0bb3n commented
In the meanwhile I added another parameter `skip` (issue #115), maybe the the corresponding PR #116 helps you to updated your PR.

2021-07-16 07:44 UTC, markri commented
Well... I guess I was being a bit hasty. As it turns out we went down a different path. So I don't mind closing this PR

The underlying problem was that that the Jenkins Quality Gate plugin doesn't seem to work with Sonar 8.9 LTS, hence I was in need of re-implementing that behaviour in a different way. Ultimately I went for a small system groovy script that is being executed as a post step in a Maven job (not pipeline job, as that is much simpler to implement). This is a bit of a wrong place to share that script (as I still value this plugin and know that it can be hard to succesfully maintain an open source project, so hats of to you!). But it still might help others who want to mark their build as unstable.

```
@Grab('com.github.groovy-wslite:groovy-wslite:1.1.2')

import wslite.http.auth.*
import wslite.rest.*

def URL = build.getEnvironment(listener).get('SONAR_HOST_URL')
def TOKEN = build.getEnvironment(listener).get('SONAR_AUTH_TOKEN')
def component = "<replace_this_with_your_component_id>"

RESTClient client = new RESTClient(URL)
client.authorization = new HTTPBasicAuthorization(TOKEN, '')

def response
def itemsInQueue = true

while (itemsInQueue) {
    response = client.get(
            path: "/api/ce/component?component=${component}",
            headers: ["Content-Type": "application/json"]
    )

    itemsInQueue = response.json.queue.size() > 0
    println ("Polling SonarQube for Quality Gate status")
    sleep(5000)
}


def qgresponse = client.get(
        path: "/api/qualitygates/project_status?projectKey=${component}",
        headers: ["Content-Type": "application/json"]
)

println ("Quality Gate status: ${qgresponse.json.projectStatus.status}")

if (qgresponse.json.projectStatus.status != 'OK'){
    build.result = hudson.model.Result.UNSTABLE
}


```

2021-07-16 07:44 UTC, closed without merging

2021-07-17 19:33 UTC, r0bb3n commented
No worries and thanks for sharing your solution 👍 

I will still follow up your requested feature, because it makes totally sense to have something like this built in.